"""Meta variables for SkLite"""
__title__ = "sklite"
__version__ = "0.0.2"
__description__ = "Use Scikit Learn models in Flutter"
__url__ = "https://github.com/axegon/sklite"
__author__ = "Alexander Ejbekov"
__author_email__ = "alexander@kialo.ai"
__license__ = "MIT"
__compat__ = "0.0.1"
